src/objects/DMRNoteProxy__c.object
<CustomObject>
    <description>This object enables bulk import of ContentNote records. Import to this object with content and linking details, then use the list views or Apex DMRNoteBulkImporter to convert to note records..</description>
    <fields>
        <fullName>Content__c</fullName>
        <label>Content</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Error__c</fullName>
        <label>Error</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Imported__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Imported</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LinkedTo__c</fullName>
        <label>Linked To</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Note_ID__c</fullName>
        <label>Note ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShareType__c</fullName>
        <label>ShareType</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Visibility__c</fullName>
        <label>Visibility</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <label>Note Proxy</label>
    <nameField>
        <displayFormat>NP-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Note Proxies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DMRNoteBulkImporter.cls
// DMRNoteBulkImporter.cls
// (c) 2016 David Reed
// Available under the terms of the MIT License.

public class DMRNoteBulkImporter implements Database.Batchable<sObject> {
    private List<Id> noteProxyIDs;

    public DMRNoteBulkImporter(List<Id> proxies) {
        noteProxyIDs = new List<Id>(proxies);
    }

    // Limits usage: 1 SOQL query; 0 DML operations
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([SELECT Title__c, Content__c, LinkedTo__c, Visibility__c, ShareType__c
                                         FROM DMRNoteProxy__c
                                         WHERE Id in :noteProxyIDs]);
    }

    // Limits usage: 0-2 SOQL queries (from DMRNoteAttachmentImporter.insertRecords()), 3 DML operations (2 inherited + 1)
    public void execute(Database.BatchableContext bc, List<sObject> noteProxies) {
        DMRNoteAttachmentImporter im = new DMRNoteAttachmentImporter();

        for (sObject np : noteProxies) {
            DMRNoteProxy__c proxy = (DMRNoteProxy__c)np;
            
            im.addNote(proxy.Title__c, proxy.Content__c, proxy.LinkedTo__c, proxy.Visibility__c, proxy.ShareType__c);
        }

        im.insertRecords();
        
        for (Integer i = 0; i < im.results.size(); i++) {
            DMRNoteProxy__c proxy = (DMRNoteProxy__c)noteProxies[i];

            if (im.results[i].isSuccess()) {
                proxy.Imported__c = true;
                proxy.Error__c = '';
                proxy.Note_ID__c = im.results[i].getId();
            } else {
                Database.Error err = im.results[i].getErrors()[0];
                proxy.Imported__c = false;
                proxy.Error__c = err.getStatusCode() + ': ' + err.getMessage();
            }
        }
        
        update noteProxies;
    }

    public void finish(Database.BatchableContext bc) {

    }
}